"""
fig_refraction_field_data_synthetic.py

Scientific content:
    Three-panel figure reproducing the type of data obtained in a shallow
    seismic refraction survey with a sledgehammer source and geophone array.

    Panel A: Synthetic wiggle-trace shot gather (13 geophones, 3 m spacing,
      offsets 5–38 m). Generated by convolving a Ricker wavelet (120 Hz)
      with the first-arrival time at each offset. Reproduces the qualitative
      character of W.W. Norton Fig 3.6 (Burger et al., Introduction to
      Applied Geophysics, 2006) — no text or data reproduced; all values
      and rendering are original.

    Panel B: Raw first-arrival picks (T vs. x).

    Panel C: Line-fitted picks with slope-intercept inversion result.

    Velocity model follows the field example context of Norton Fig 3.7g:
      V1 ~ 350 m/s (dry sand), V2 ~ 1500 m/s (saturated), H ~ 5 m.

Output: assets/figures/fig_refraction_field_data_synthetic.png
License: CC-BY 4.0 (this script)
Author:  ESS 314 course, University of Washington, 2026
"""

import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from scipy.signal import fftconvolve
import os

mpl.rcParams.update({
    "font.size": 12,
    "axes.titlesize": 12,
    "axes.labelsize": 12,
    "xtick.labelsize": 11,
    "ytick.labelsize": 11,
    "legend.fontsize": 10,
    "figure.dpi": 150,
})

BLUE      = "#0072B2"
ORANGE    = "#E69F00"
GREEN     = "#009E73"
BLACK     = "#000000"
VERMILION = "#D55E00"

# ── Model ──────────────────────────────────────────────────────────────────────
V1   = 350.0
V2   = 1500.0
H    = 5.0
rng  = np.random.default_rng(42)

theta_c = np.arcsin(V1 / V2)
t_i     = 2 * H * np.cos(theta_c) / V1
x_crit  = 2 * H * np.tan(theta_c)
x_cross = 2 * H * np.sqrt((V2 + V1) / (V2 - V1))

geo_x = np.arange(5, 42, 3)          # 5, 8, 11, … 38 m
n_geo = len(geo_x)

def t_direct(x):
    return np.atleast_1d(np.asarray(x, float)) / V1

def t_head(x):
    x = np.atleast_1d(np.asarray(x, float))
    t = x / V2 + t_i
    t[x < x_crit] = np.nan
    return t

def first_arrival(x):
    td = t_direct(x)
    th = t_head(x)
    mask = ~np.isnan(th) & (th < td)
    fa   = td.copy()
    fa[mask] = th[mask]
    return fa

# ── Ricker wavelet ──────────────────────────────────────────────────────────
dt    = 0.0002
f0    = 120.0
t_end = 0.130
t_vec = np.arange(0, t_end, dt)
n_t   = len(t_vec)

def ricker_wavelet(f, dt, n):
    t_half = np.arange(-(n // 2), n // 2 + 1) * dt
    w = (1 - 2 * np.pi**2 * f**2 * t_half**2) * np.exp(
        -np.pi**2 * f**2 * t_half**2)
    return w

wvlt = ricker_wavelet(f0, dt, 81)
fa_times = first_arrival(geo_x)

traces = np.zeros((n_geo, n_t))
for i, (x, t_fa) in enumerate(zip(geo_x, fa_times)):
    idx = int(t_fa / dt)
    spike = np.zeros(n_t)
    if 0 <= idx < n_t:
        spike[idx] = 1.0
    tr = fftconvolve(spike, wvlt, mode="same")
    tr += rng.normal(0, 0.015, n_t)
    peak = np.max(np.abs(tr))
    traces[i] = tr / (peak + 1e-12)

# ── Figure — taller to give each panel room ─────────────────────────────────
fig = plt.figure(figsize=(8.5, 11))
gs  = fig.add_gridspec(3, 1, height_ratios=[2.2, 1, 1], hspace=0.52)
ax_sg  = fig.add_subplot(gs[0])
ax_raw = fig.add_subplot(gs[1])
ax_fit = fig.add_subplot(gs[2])

t_ms = t_vec * 1e3
scale = 1.5

# ── Panel A: Shot gather ────────────────────────────────────────────────────
for i in range(n_geo):
    x_off = geo_x[i]
    tr    = traces[i] * scale
    ax_sg.plot(t_ms, x_off + tr, color=BLUE, lw=0.7, alpha=0.85)
    ax_sg.fill_betweenx(
        x_off + tr,
        t_ms,
        x_off,
        where=(tr > 0),
        color=BLUE, alpha=0.30,
    )
    fa_ms = fa_times[i] * 1e3
    ax_sg.plot(fa_ms, x_off, "^", ms=5, color=VERMILION, zorder=5)

# Down-arrow annotations marking the arrival trend — spaced to avoid overlap
for x_arr in [8, 20, 35]:
    idx_g = int(np.argmin(np.abs(geo_x - x_arr)))
    ax_sg.annotate(
        "", xy=(fa_times[idx_g] * 1e3, geo_x[idx_g]),
        xytext=(fa_times[idx_g] * 1e3, geo_x[idx_g] + 4),
        arrowprops=dict(arrowstyle="-|>", color=VERMILION, lw=1.2),
    )

ax_sg.set_xlabel("Time (ms)")
ax_sg.set_ylabel("Distance (m)")
ax_sg.set_title(
    "(a) Synthetic shot gather — sledgehammer, 3 m geophone spacing\n"
    r"$V_1=350$ m/s (dry sand), $V_2=1500$ m/s (saturated)"
)
ax_sg.set_xlim(0, t_end * 1e3)
ax_sg.set_ylim(2, 41)
ax_sg.invert_yaxis()

# Legend anchored inside upper-right — data is concentrated in the left-centre
from matplotlib.lines import Line2D
leg_handles = [
    Line2D([0], [0], marker="^", color="w",
           markerfacecolor=VERMILION, markersize=7,
           label="First-arrival pick"),
    mpl.patches.Patch(facecolor=BLUE, alpha=0.6,
                      label="Positive wiggle fill"),
]
ax_sg.legend(handles=leg_handles, loc="lower right",
             fontsize=9, framealpha=0.90, edgecolor="gray")

# ── Panel B: Raw picks ──────────────────────────────────────────────────────
ax_raw.scatter(geo_x, fa_times * 1e3, s=50, color=BLACK, zorder=4,
               label="First-arrival picks")
ax_raw.set_xlim(-1, 42)
ax_raw.set_ylim(0, 55)
ax_raw.set_xlabel("Distance (m)")
ax_raw.set_ylabel("Time (ms)")
ax_raw.set_title("(b) First-arrival picks — raw data")

# Mark crossover region with a subtle shaded band — no overlapping text needed
ax_raw.axvline(x_cross, color=GREEN, lw=1.5, ls="--", alpha=0.7, zorder=3)
ax_raw.text(x_cross + 0.8, 3,
            r"$x_\mathrm{cross}$",
            fontsize=9, color=GREEN, va="bottom")
# Legend bottom-right: data are top-left
ax_raw.legend(loc="lower right", fontsize=9,
              framealpha=0.90, edgecolor="gray")

# ── Panel C: Line fits ──────────────────────────────────────────────────────
ax_fit.scatter(geo_x, fa_times * 1e3, s=50, color=BLACK, zorder=5)

# Direct branch: use exact model line (noise-free synthetic, so fit is exact)
x_fit1 = np.array([0.0, x_cross + 2])
ax_fit.plot(x_fit1, t_direct(x_fit1) * 1e3, color=BLUE, lw=2.0,
            label=rf"Slope $=1/V_1$, $V_1={V1:.0f}$ m/s")

# Head-wave branch extended to x=0 to show intercept
x_fit2 = np.linspace(0, 42, 300)
ax_fit.plot(x_fit2, x_fit2 / V2 * 1e3 + t_i * 1e3,
            color=ORANGE, lw=2.0,
            label=rf"Slope $=1/V_2$, $V_2={V2:.0f}$ m/s")

# Intercept time tick + label (left side, no overlap with scatter)
ax_fit.plot([0], [t_i * 1e3], "o", ms=7, color=ORANGE, zorder=6)
ax_fit.annotate(
    rf"$t_i={t_i*1e3:.1f}$ ms",
    xy=(0, t_i * 1e3),
    xytext=(4, t_i * 1e3 + 4),
    fontsize=9, color=ORANGE,
    arrowprops=dict(arrowstyle="-", color=ORANGE, lw=0.8),
)

# Crossover
ax_fit.axvline(x_cross, color=GREEN, lw=1.5, ls="--", alpha=0.7, zorder=3)
ax_fit.text(x_cross + 0.8, 4,
            rf"$x_\mathrm{{cross}}\approx{x_cross:.1f}$ m",
            fontsize=9, color=GREEN, va="bottom")

ax_fit.set_xlim(-1, 42)
ax_fit.set_ylim(0, 55)
ax_fit.set_xlabel("Distance (m)")
ax_fit.set_ylabel("Time (ms)")
ax_fit.set_title(
    r"(c) Slope-intercept inversion: $V_1$, $V_2$, $t_i \to H$"
)

# Legend: upper-left — data plots mostly in the lower half
ax_fit.legend(loc="upper left", fontsize=9,
              framealpha=0.90, edgecolor="gray")

# Result box anchored to lower-right corner — well separated from legend
result_text = (
    rf"$V_1={V1:.0f}$ m/s, $V_2={V2:.0f}$ m/s" + "\n"
    rf"$t_i={t_i*1e3:.1f}$ ms $\Rightarrow$ $H={H:.1f}$ m"
)
ax_fit.text(
    0.99, 0.06, result_text,
    transform=ax_fit.transAxes, fontsize=9,
    ha="right", va="bottom",
    bbox=dict(boxstyle="round,pad=0.45", facecolor="white",
              edgecolor="gray", alpha=0.92),
)

# ── Save ────────────────────────────────────────────────────────────────────
os.makedirs("assets/figures", exist_ok=True)
out = "assets/figures/fig_refraction_field_data_synthetic.png"
fig.savefig(out, dpi=150, bbox_inches="tight")
print(f"Saved: {out}")
plt.close()
